name = "gh-automation"
main = "src/index.js"
compatibility_date = "2026-06-03"
workers_dev = true

[[kv_namespaces]]
binding = "CAPTURE_KV"
id = "50756bcd409148daae31da9f4cf4ee2c"

[vars]
GITHUB_REPO = "univcorp2-ctrl/chatgpt-worker-smoketest"
# URL_SECRET, GITHUB_TOKEN should be configured with wrangler secret put.
